

def omega_help():
    print('')
    print(' [OmegaFind v2]  [Version 2. Multi-processed async for better performance]')
    print('                 [Forensics tool. Search differently]')
    print('')
    print(' [--learn]             [Scans and learns from specified target location]')
    print(' [--chunk-max]         [Maximum items in each chunk. (Default 16)]')
    print(' [--buffer-max]        [Maximum bytes read. (Default 1024)]')
    print(' [--database]          [Specify a database file to use for scanning]')
    print(' [--new-suffix-group]  [Create a new suffix group]')
    print(' [--clean-db]          [Removes any duplicates and empty lines]')
    print('')
    print(' [Scan Techniques]')
    print(' [--de-scan]    [Attempt to ascertain if file(s) suffix matches its contents]')
    print(' [--type-scan]  [Scan and compare files to known suffix/buffer relationships]')
    print('                [--suffix]         [Suffix resolves to buffer data in DB]')
    print('                [--custom-suffix]  [Select a custom suffix group]')
    print('                [--group-suffix]   [Suffix(s) resolve to buffer data in DB]')
    print('                                   [archive]')
    print('                                   [audio]')
    print('                                   [book]')
    print('                                   [code]')
    print('                                   [executable]')
    print('                                   [font]')
    print('                                   [image]')
    print('                                   [sheet]')
    print('                                   [slide]')
    print('                                   [text]')
    print('                                   [video]')
    print('                                   [web]')
    print('')
    print(' [Examples]')
    print(' [omega_find --learn PATH --chunk-max 16 --buffer-max 1024 -v]')
    print(' [omega_find --de-scan PATH --chunk-max 16 --buffer-max 1024 -v]')
    print(' [omega_find --type-scan PATH --suffix sh -v]')
    print(' [omega_find --type-scan PATH --custom-suffix -v]')
    print(' [omega_find --type-scan PATH --group-suffix image]')
    print('')
    print(' [-v]  [Verbosity]  [Increase verbosity]')
    print(' [-h]  [Help]       [Displays this help message]')
    print('')
