import omega_find_banner


def omega_help():
    omega_find_banner.banner()
    print(' -l       Learn                 Specify location to learn from.')
    print(' -r       Reveal                Display all file types.')
    print(' -p       Password Protected    Only scan for password protected archives.')
    print(' -d       De-Obfuscation        Attempt to find files where suffix does not match contents.')
    print(' -t       Type                  Display all files of type.')
    print(' -sfx     Suffix                Specify suffix. Used with -t.')
    print(' -csfx    Custom Suffix         Specify custom suffix group. Used with -t.')
    print(' -gsfx    Group Suffix          Specify default group suffix group. Used with -t.')
    print('                                archive, audio, book, code, exe, font, image, sheet, slide, text, video, web.')
    print(' -nsfx    New Suffix Group      Create new custom suffix group.')
    print(' -e       Extract               Attempt to extract archive while scanning.')
    print(' -db      Database              Specify database to use while learning/scanning.')
    print(' -cmax    Chunk Max             Specify in digits max items to be processed at any one time.')
    print(' -bmax    Buffer Max            Specify in digits maximum number of bytes to read of each file.')
    print(' -R       Recognized            Display current learning XP.')
    print('')
    print(' -v       Verbosity             Increase verbosity.')
    print(' -h       Help                  Display this help message.')
    print('')
    print(' [Author] Developed and written by Benjamin Jack Cullen.')
    print('')
